#!/usr/bin/env bash

_outc="$1"
_outh="$2"
_name="$3"
_in="$4"

xxd -i -n "$_name" < "${_in}" > "${_outc}"

def=$(sed -E 's/(.*)/\U\1/g' <<< "$(basename $_outh)" | sed -E 's/([\.|\/|-])/_/g' | tr ' ' '_')
{
    echo "/** Automatically generated by the build system from $_in"
    echo "  * !!! ANY MODIFICATION OF THIS FILE WILL BE DISCARDED !!!"
    echo "  * Generation date: $(date)"
    echo "  **/"
    echo "#ifndef $def"
    echo "#define $def"
    echo
    grep unsigned | sed -E 's/(unsigned.*)=.*/extern \1;/g'
    echo
    echo "#endif //$def"
} < "$_outc" > "$_outh"
