#!/usr/bin/env bash
set -euo pipefail
_outc="$1"
_outh="$2"
_name="$3"
_in="$4"
_compress_cmd="$5"
compress_out=/tmp/"$(basename "${_in}").Z"

"$_compress_cmd" "${_in}" "$compress_out"
xxd -i -n "$_name" < "${compress_out}" > "${_outc}"
rm "$compress_out"

def=$(sed -E 's/(.*)/\U\1/g' <<< "$(basename "$_outh")" | sed -E 's/([\.|\/|-])/_/g' | tr ' ' '_')
{
    echo "/** Automatically generated by the build system from $_in"
    echo "  * !!! ANY MODIFICATION OF THIS FILE WILL BE DISCARDED !!!"
    echo "  * Generation date: $(date)"
    echo "  **/"
    echo "#ifndef $def"
    echo "#define $def"
    echo
    grep unsigned | sed -E 's/(unsigned.*)=.*/extern \1;/g'
    echo
    echo "#endif //$def"
} < "$_outc" > "$_outh"
