name: Cygwin (Windows) Nightly Build

on:
  workflow_dispatch:    # Enables manual triggering
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  issues: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Avoid CRLF
      - name: Git line endings
        run: git config --global core.autocrlf input

      - uses: actions/checkout@v4

      - name: Set up Cygwin (cmake, make, gcc/g++, xxd)
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: cmake make gcc-g++ xxd

      - name: Configure (Cygwin)
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          cd /cygdrive/d/a/ccdb/ccdb
          cmake -S src -DCMAKE_MAKE_PROGRAM=/usr/bin/make -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCCDB_CYGWIN_BUILD=True -DNCURSES_MAKE_ADDITIONAL_FLAGS=-j2 -DREADLINE_MAKE_ADDITIONAL_FLAGS=-j2

      - name: Build (Cygwin)
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          cd /cygdrive/d/a/ccdb/ccdb
          cmake --build build -- -j2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cygwin-build
          path: C:\tools\cygwin\cygdrive\d\a\ccdb\ccdb\build\ccdb.exe
