name: Cygwin (Windows) Nightly Build

on:
  workflow_dispatch:    # Enables manual triggering
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  issues: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Avoid CRLF
      - name: Git line endings
        run: git config --global core.autocrlf input

      - uses: actions/checkout@v4

      - name: Set up Cygwin (cmake, make, gcc/g++, xxd)
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: cmake make gcc-g++ xxd

      - name: Configure (Cygwin)
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          cd /cygdrive/d/a/ccdb/ccdb
          cmake -S src -DCMAKE_MAKE_PROGRAM=/usr/bin/make -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCCDB_CYGWIN_BUILD=True -DNCURSES_MAKE_ADDITIONAL_FLAGS=-j$(nproc) -DREADLINE_MAKE_ADDITIONAL_FLAGS=-j$(nproc)

      - name: Build (Cygwin)
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          cd /cygdrive/d/a/ccdb/ccdb
          cmake --build build -- -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cygwin-build
          path: D:\a\ccdb\ccdb\build\ccdb.exe

      - name: Get Git commit hash
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        id: get_commit
        run: |
          cd /cygdrive/d/a/ccdb/ccdb
          echo "GIT_HASH=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV

      - name: Set up Git for pushing tag
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          cd /cygdrive/d/a/ccdb/ccdb
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Create Git tag for release
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          cd /cygdrive/d/a/ccdb/ccdb
          git tag "ccdb.cygwin.NightlyBuild.${{ env.GIT_HASH }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} "ccdb.cygwin.NightlyBuild.${{ env.GIT_HASH }}"

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: D:\a\ccdb\ccdb\build\ccdb.exe
          tag_name: "ccdb.cygwin.NightlyBuild.${{ env.GIT_HASH }}"
          prerelease: true  # Marking this as a pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ccdb.cygwin.NightlyBuild.${{ env.GIT_HASH }}
